apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/traefik-crd.yml
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: bk7987/opuscm-users
      context: users
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: bk7987/opuscm-submittals
      context: submittals
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.py'
            dest: .
    - image: bk7987/opuscm-notifications
      context: notifications
      docker:
        dockerfile: dev.Dockerfile
      sync:
        manual:
          - src: 'src/**/*.go'
            dest: .
