kind: Deployment
apiVersion: apps/v1
metadata:
  name: organizations-depl
  labels:
    app: organizations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizations
  template:
    metadata:
      labels:
        app: organizations
    spec:
      containers:
        - name: organizations
          image: bk7987/opuscm-organizations
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: firebase-config
              mountPath: '/app/secrets'
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './secrets/firebase-admin-config.json'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: nats-cluster-id
                  key: NATS_CLUSTER_ID
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_QUEUE_GROUP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: pg-user
                  key: PG_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: PG_PASSWORD
            - name: PG_DATABASE
              value: organizations
            - name: PG_HOST
              value: 'organizations-db-srv'
      volumes:
        - name: firebase-config
          secret:
            secretName: firebase-config

---
kind: Service
apiVersion: v1
metadata:
  name: organizations-srv
spec:
  selector:
    app: organizations
  ports:
    - name: organizations
      protocol: TCP
      port: 3000
      targetPort: 3000
