kind: Deployment
apiVersion: apps/v1
metadata:
  name: submittals-depl
  labels:
    app: submittals
spec:
  replicas: 1
  selector:
    matchLabels:
      app: submittals
  template:
    metadata:
      labels:
        app: submittals
    spec:
      containers:
        - name: submittals
          image: bk7987/opuscm-submittals
          imagePullPolicy: IfNotPresent
---
kind: Service
apiVersion: v1
metadata:
  name: submittals-srv
spec:
  selector:
    app: submittals
  ports:
    - name: submittals
      protocol: TCP
      port: 3000
      targetPort: 3000
