apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
        - name: projects
          image: bk7987/opuscm-projects
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: firebase-config
              mountPath: '/app/secrets'
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './secrets/firebase-admin-config.json'
            - name: NATS_URL
              value: 'http://nats-srv:4222'
      volumes:
        - name: firebase-config
          secret:
            secretName: firebase-config
---
apiVersion: v1
kind: Service
metadata:
  name: projects-srv
spec:
  selector:
    app: projects
  ports:
    - name: projects
      protocol: TCP
      port: 3000
      targetPort: 3000
