FROM python:3.8-alpine

RUN pip install pipenv
WORKDIR /app
COPY Pipfile* ./
RUN pipenv lock --requirements > requirements.txt
RUN pip install -r requirements.txt
COPY ./ ./

CMD ["uvicorn", "src.main:app", "--reload", "--port=3000"]